name: Download BERT Model

on:
  push:
    branches: [main]  # Trigger on pushes to main branch
  pull_request:
    branches: [main]  # Trigger on pull requests to main

jobs:
  download:
    runs-on: ubuntu-latest  # Use Ubuntu for better compatibility

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Latest version for reliability

    - name: Set up Python
      uses: actions/setup-python@v5  # Latest version
      with:
        python-version: '3.10'  # Matches your local Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transformers tensorflow tf-keras safetensors tensorflow-hub
        # Optional: Install dependencies for jarvis.py
        pip install wikipedia pyttsx3 pyaudio spacy fuzzywuzzy pillow matplotlib
        python -m spacy download en_core_web_sm

    - name: Run download_bert.py
      env:
        TF_ENABLE_ONEDNN_OPTS: 0  # Disable oneDNN to avoid numerical differences
      run: python download_bert.py

    - name: Verify model files
      run: |
        ls -la bert_model/  # List files to confirm tf_model.h5 exists
        echo "Model files:"
        ls bert_model/

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bert-model
        path: bert_model/
        retention-days: 7  # Keep artifact for 7 days
